language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --white-list circe.io,sindresorhus/awesome,orderly-json,hearthstonejson,oboejs,awesometelegram,core.telegram.org,storebot.me,reddit.com,dev.storebot.me
